// SESSION MODULE
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const AUTHENTIFICATION_FAIL = 'AUTHENTIFICATION_FAIL';
export const AUTHENTIFICATION_SUCCESS = 'AUTHENTIFICATION_SUCCESS';
export const AUTHENTIFICATION_START = 'AUTHENTIFICATION_START';
export const RESET_SESSION = 'RESET_SESSION';

// ADMIN MODULE
export const SET_DASHBAORDS = 'SET_DASHBAORDS';
