// SESSION MODULE
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER = 'SET_USER';
export const AUTHENTIFICATION_FAIL = 'AUTHENTIFICATION_FAIL';
export const AUTHENTIFICATION_SUCCESS = 'AUTHENTIFICATION_SUCCESS';
export const AUTHENTIFICATION_START = 'AUTHENTIFICATION_START';
export const RESET_SESSION = 'RESET_SESSION';

// ADMIN MODULE
export const SET_DASHBAORDS = 'SET_DASHBAORDS';
export const SET_DASHBAORD = 'SET_DASHBAORD';
export const DASHBOARDS_START_LOADING = 'DASHBOARDS_START_LOADING';
export const DASHBOARDS_LOADED = 'DASHBOARDS_LOADED';

export const SET_WIDGET = 'SET_WIDGET';
export const WIDGETS_START_LOADING = 'WIDGETS_START_LOADING';
export const WIDGETS_LOADED = 'WIDGETS_LOADED';

// UI MODULE
export const SET_WINDOW_SIZE = 'SET_WINDOW_SIZE';
